include: package:very_good_analysis/analysis_options.yaml

analyzer:
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true
  errors:
    missing_return: error
    missing_required_param: error
    must_be_immutable: error
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "example/**"

linter:
  rules:
    # Type safety
    avoid_dynamic_calls: true
    always_declare_return_types: true
    prefer_typing_uninitialized_variables: true
    type_annotate_public_apis: true

    # Error handling
    only_throw_errors: true
    use_rethrow_when_possible: true

    # Code quality
    prefer_const_constructors: true
    prefer_const_declarations: true
    prefer_final_fields: true
    prefer_final_locals: true
    unnecessary_await_in_return: true
    unnecessary_lambdas: true

    # Temporarily disabled until dynamic removal is complete
    # avoid_catches_without_on_clauses: true

    # Documentation - enable after initial cleanup
    # public_member_api_docs: true
    # package_api_docs: true
